# Project information
site_name: Jinay Shah's Notebook
site_author: Jinay Shah
site_url: https://jinayshah.netlify.com
site_description: This is jinay shah's notebook

# Repository
repo_url: https://github.com/jinayshah86/notebook.git
repo_name: jinayshah86/notebook

# Navigation
nav:
  - Home: 'index.md'
  - Python:
      - Functions: 'python/functions.md'
      - Decorators: 'python/decorators.md'
      - OOP: 'python/oop.md'
      - References: 'python/references.md'

# Plugin
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
  - git-revision-date-localized:
      type: timeago

# Extension
markdown_extensions:
  - smarty
  - footnotes
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Customization
theme:
  name: material
  language: en
  font:
    text: 'Roboto Mono'
    code: 'Hack'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/jinayshah86'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/jinay-shah-46515ab6/'
