# Project information
site_name: Mickey Mouse's Notebook
site_author: Mickey Mouse
site_url: https://jinayshah.netlify.com
site_description: This is mickey mouse's notebook

# Navigation
nav:
  - Home: 'index.md'
  - Python:
      - Functions: 'python/functions.md'
      - Decorators: 'python/decorators.md'
      - OOP: 'python/oop.md'
      - Iterator: 'python/iterator.md'
      - Working with files: 'python/files.md'
      - 'python/custom-json.md'
      - References: 'python/references.md'

# Plugin
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
  - git-revision-date-localized:
      type: timeago

# Extension
markdown_extensions:
  - smarty
  - footnotes
  - admonition
  - codehilite
  - fontawesome_markdown
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

# Customization
theme:
  name: material
  language: en
  font:
    text: 'Roboto Mono'
    code: 'Hack'

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
